name: CI/CD

on:
  push:
    branches:
      - deploy
    paths-ignore:
      - README.md

jobs:
  build-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          bode-version: ${{ matrix.node-version }}
        
        - name: Install dependencies
          run: npm install
        
        - name: Build
          run: npm run build --if-present
        
        - names: Deploy to Server
          uses: 
          env:
            DEPLOY_Key: ${{ SECRETS.DEPLOY_KEY }}
            ARGS: -avz --delete --exclude='*.pyc'
            SOURCE: "./build/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.SSH_USERNAME }}
            TARGET: ${{ secrets.REMOTE_TARGET }}